
openapi: 3.1.0
info:
  title: Meal Logger
  version: '1.0'
paths:
  /log:
    post:
      operationId: logMeal
      summary: Logs a meal entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                meal:
                  type: string
                  description: The meal to log
              required:
                - meal
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
